name: Argo CD GitOps CI/CD

on:
  push:
    branches:
    - main
    paths:
    - 'main.go'


jobs:
  build:
    name: Build and Push the image
    runs-on: [self-hosted]
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: pathcl/go-server:${{ github.sha }} , pathcl/go-server:latest

  update:
    name: Update Helm Manifests
    runs-on: [self-hosted]
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update Image Tag Values
      run: |
        chart_dir="chart"
        new_image_tag=${{ github.sha }}

        # Update the values.yaml file with the new image tag
        sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"
    
    - name: Commit the changes made
      run: | 
        git config --global user.name 'Luis San Martin'
        git config --global user.email 'luis@sanmartin.io'
        git commit -am "updating image tag"
        git push